version: 2
jobs:
  build:
    docker:
      - image: vaporio/build-base:7582146
    working_directory: ~/code

    steps:
      - checkout

      - setup_remote_docker:
          reusable: true
          exclusive: false

      - run:
          name: Docker Private Images (temporary)
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PS

      - run:
          name: Run the tests.
          command: |
            make config-volume build circleci
